export { MainPage } from './main'
export { EventsPage } from './events'
export { EventPage } from './event'
export { MyApplicationsPage } from './my-applications'
export { NotificationsPage } from './notifications'
export { ProfilePage } from './profile'
export { CreateEventPage } from './create-event'
export { ManageEventPage } from './manage-event'
export { AuthPage, LoginPage, RegisterPage } from './auth'
export { AdminPage } from './admin'
